apiVersion: 1

datasources:
  - name: InfluxDB_Flux
    uid: influxdbFlux
    type: influxdb
    access: proxy
    url: http://$INFLUXDB_ADDRESS:8086
    jsonData:
      version: Flux
      organization: $DOCKER_INFLUXDB_INIT_ORG
      defaultBucket: $GRAFANA_INFLUXDB_DEFAULT_BUCKET
      tlsSkipVerify: true
    secureJsonData:
      token: $DOCKER_INFLUXDB_INIT_ADMIN_TOKEN

  - name: InfluxDB_InfluxQL
    uid: influxdbQL
    type: influxdb
    access: proxy
    url: http://$INFLUXDB_ADDRESS:8086
    jsonData:
      dbName: $GRAFANA_INFLUXDB_DEFAULT_BUCKET
      httpHeaderName1: "Authorization"
    secureJsonData:
      httpHeaderValue1: "Token $DOCKER_INFLUXDB_INIT_ADMIN_TOKEN"
