vrrp_script chk_kafka {
    script "/bin/sh -c 'nc -z localhost 9094'"
    interval 2  # Check every 2 seconds
    weight -10  # Decrease priority by 10 if the check fails
    timeout 5   # Add a timeout for the script to prevent hanging
}

vrrp_script chk_telegraf {
    script "/bin/sh -c 'curl -s -o /dev/null -w '%{http_code}' http://localhost:8000 | grep -q 200'"
    interval 2  # Check every 2 seconds
    weight -10  # Decrease priority by 10 if the check fails
    timeout 5   # Add a timeout for the script to prevent hanging
}

vrrp_instance VI_1 {
    state BACKUP
    interface ens19
    virtual_router_id 51
    priority 100  # Lower priority for the backup
    advert_int 1
    authentication {
        auth_type PASS
        auth_pass REDACTED
    }
    virtual_ipaddress {
        10.0.0.50
    }
    track_script {
        chk_kafka
        chk_telegraf
    }
}
