services:
  telegraf:
    restart: unless-stopped
    image: telegraf:1.33-alpine
    user: telegraf:$DOCKER_GID
    volumes:
      - $CONFIG_PATH/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - $CONFIG_PATH/telegraf/telegraf.d/:/etc/telegraf/telegraf.d/:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /:/hostfs:ro
    environment:
      - HOSTNAME=$HOSTNAME
      - INFLUXDB_ADDRESS=$INFLUXDB_ADDRESS
      - DOCKER_INFLUXDB_INIT_ORG=$DOCKER_INFLUXDB_INIT_ORG
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=$DOCKER_INFLUXDB_INIT_ADMIN_TOKEN
      - HOST_MOUNT_PREFIX=/hostfs
      - HOST_PROC=/hostfs/proc
    ports:
      - "8125:8125"
      - "8000:8000"
    healthcheck:
      test: wget --no-verbose --tries=1 --spider localhost:8000 || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
