services:
  influxdb:
    restart: unless-stopped
    image: influxdb:2.7-alpine
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=$DOCKER_INFLUXDB_INIT_USERNAME
      - DOCKER_INFLUXDB_INIT_PASSWORD=$DOCKER_INFLUXDB_INIT_PASSWORD
      - DOCKER_INFLUXDB_INIT_ORG=$DOCKER_INFLUXDB_INIT_ORG
      - DOCKER_INFLUXDB_INIT_BUCKET=cisco_mdt
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=$DOCKER_INFLUXDB_INIT_ADMIN_TOKEN
    ports:
      - "8086:8086"
    volumes:
      - $INFLUXDB_DATA_PATH:/var/lib/influxdb2:rw
    healthcheck:
      test: "curl --fail -s http://localhost:8086/health | grep -q pass"
      interval: 30s
      timeout: 10s
      retries: 5

  influxdb_init:
    links:
      - influxdb
    image: influxdb:2.7-alpine
    entrypoint: ["/bin/sh", "-c"]
    command: |
      "
      until influx org list --host http://influxdb:8086 --token $DOCKER_INFLUXDB_INIT_ADMIN_TOKEN | grep $DOCKER_INFLUXDB_INIT_ORG; do
        echo 'Waiting for organization $DOCKER_INFLUXDB_INIT_ORG to be created...';
        sleep 2;
      done;
      influx bucket create --skip-verify --name influx_metrics    --retention 30d --org $DOCKER_INFLUXDB_INIT_ORG --host http://influxdb:8086 --token $DOCKER_INFLUXDB_INIT_ADMIN_TOKEN
      influx bucket create --skip-verify --name node_telemetry    --retention 30d --org $DOCKER_INFLUXDB_INIT_ORG --host http://influxdb:8086 --token $DOCKER_INFLUXDB_INIT_ADMIN_TOKEN
      influx bucket create --skip-verify --name docker_metrics    --retention 30d --org $DOCKER_INFLUXDB_INIT_ORG --host http://influxdb:8086 --token $DOCKER_INFLUXDB_INIT_ADMIN_TOKEN
      influx bucket create --skip-verify --name kafka_metrics     --retention 30d --org $DOCKER_INFLUXDB_INIT_ORG --host http://influxdb:8086 --token $DOCKER_INFLUXDB_INIT_ADMIN_TOKEN
      influx bucket create --skip-verify --name telegraf_metrics  --retention 30d --org $DOCKER_INFLUXDB_INIT_ORG --host http://influxdb:8086 --token $DOCKER_INFLUXDB_INIT_ADMIN_TOKEN
      influx bucket create --skip-verify --name utct_metrics  --retention 30d --org $DOCKER_INFLUXDB_INIT_ORG --host http://influxdb:8086 --token $DOCKER_INFLUXDB_INIT_ADMIN_TOKEN
      influx bucket create --skip-verify --name grafana_metrics  --retention 30d --org $DOCKER_INFLUXDB_INIT_ORG --host http://influxdb:8086 --token $DOCKER_INFLUXDB_INIT_ADMIN_TOKEN
      influx bucket create --skip-verify --name default           --retention 7d  --org $DOCKER_INFLUXDB_INIT_ORG --host http://influxdb:8086 --token $DOCKER_INFLUXDB_INIT_ADMIN_TOKEN
      "
    depends_on:
      - influxdb

  telegraf:
    restart: unless-stopped
    image: telegraf:1.33-alpine
    user: telegraf:$DOCKER_GID
    volumes:
      - $CONFIG_PATH/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - $CONFIG_PATH/telegraf/telegraf.d/:/etc/telegraf/telegraf.d/:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /:/hostfs:ro
    depends_on:
      influxdb:
        condition: service_healthy
    environment:
      - HOSTNAME=$HOSTNAME
      - DOCKER_INFLUXDB_INIT_ORG=$DOCKER_INFLUXDB_INIT_ORG
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=$DOCKER_INFLUXDB_INIT_ADMIN_TOKEN
      - KAFKA_BROKER_PRIMARY=$KAFKA_BROKER_PRIMARY
      - KAFKA_BROKER_SECONDARY=$KAFKA_BROKER_SECONDARY
      - UTCT_METRICS_URL=$UTCT_METRICS_URL
      - HOST_MOUNT_PREFIX=/hostfs
      - HOST_PROC=/hostfs/proc
    ports:
      - "8125:8125"
      - "8000:8000"
    healthcheck:
      test: wget --no-verbose --tries=1 --spider localhost:8000 || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
