services:
  keepalived:
    restart: unless-stopped
    image: osixia/keepalived:2.0.20
    network_mode: host
    configs:
      - source: keepalived_config
        target: /container/service/keepalived/assets/keepalived.conf
    cap_add:
      - NET_ADMIN
      - NET_BROADCAST
      - NET_RAW
    privileged: true
    command: [--copy-service, --loglevel, debug]
    environment:
      KEEPALIVED_COMMAND_LINE_ARGUMENTS: >-
        --log-detail
        --log-console
    healthcheck:
      test: ["CMD", "keepalived", "-v"]
      interval: 30s
      timeout: 10s
      retries: 5

  telegraf:
    restart: unless-stopped
    build: ./images/ingest/telegraf
    user: telegraf:$DOCKER_GID
    volumes:
      - $CONFIG_PATH/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - $CONFIG_PATH/telegraf/telegraf.d/:/etc/telegraf/telegraf.d/:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /:/hostfs:ro
    command: --watch-config notify --config-directory /etc/telegraf/telegraf.d/references/
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      - HOSTNAME=$HOSTNAME
      - HOST_MOUNT_PREFIX=/hostfs
      - HOST_PROC=/hostfs/proc
    ports:
      - "8125:8125"
      - "57000:57000"
      - "5000:5000"
      - "8000:8000"
    healthcheck:
        test: wget --no-verbose --tries=1 --spider localhost:8000 || exit 1
        interval: 30s
        timeout: 10s
        retries: 3

  kafka:    
    image: 'bitnami/kafka:3.9'
    restart: unless-stopped
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://$HOSTADDRESS:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics.sh --bootstrap-server kafka:9092 --list | grep -q '^telegraf$'"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - $INGEST_BUFFER_PATH:/bitnami/kafka
    ports:
      - '9094:9094'

  kafka_init:
    image: 'bitnami/kafka:latest'
    depends_on:
      - kafka
    entrypoint: [ '/bin/sh', '-c' ]
    command: |
      "
      # blocks until kafka is reachable
      kafka-topics.sh --bootstrap-server kafka:9092 --list

      echo -e 'Creating kafka topics'
      kafka-topics.sh --bootstrap-server kafka:9092 --create --if-not-exists --topic telegraf --replication-factor 1 --partitions 1

      echo -e 'Successfully created the following topics:'
      kafka-topics.sh --bootstrap-server kafka:9092 --list
      "

  kafka-ui:
    restart: unless-stopped
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'
      AUTH_TYPE: "LOGIN_FORM"
      SPRING_SECURITY_USER_NAME: $KAFKA_UI_USER
      SPRING_SECURITY_USER_PASSWORD: $KAFKA_UI_PASSWORD
      KAFKA_CLUSTERS_0_NAME: kafka
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    depends_on:
      - kafka
    ports:
      - '8080:8080'
    healthcheck:
      test: wget --no-verbose --tries=1 --spider localhost:8080 || exit 1
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 30s


  kafka-exporter:
    restart: unless-stopped
    image: docker.io/bitnami/kafka-exporter:latest
    depends_on:
      kafka:
        condition: service_healthy
    command: --kafka.server=kafka:9092
    healthcheck:
      test: "bash -c 'printf \"\" > /dev/tcp/127.0.0.1/9308; exit $$?;'"
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 5s

configs:
  keepalived_config:
    content: |
      vrrp_script chk_kafka {
        script "/bin/sh -c 'nc -z localhost 9094'"
        interval 2  
        weight -10  
        timeout 5   
      }

      vrrp_script chk_telegraf {
        script "/bin/sh -c 'curl -s -o /dev/null -w '%{http_code}' http://localhost:8000 | grep -q 200'"
        interval 2  
        weight -10  
        timeout 5   
      }
      
      vrrp_instance VI_1 {
        state ${KEEPALIVED_STATE}
        interface ${KEEPALIVED_INTERFACE}
        virtual_router_id 95
        priority ${KEEPALIVED_NODE_PRIORITY}  
        advert_int 1
        authentication {
          auth_type PASS
          auth_pass ${KEEPALIVED_AUTH_PASS}
        }
        virtual_ipaddress {
            172.0.0.50
        }
        track_script {
            chk_kafka
            chk_telegraf
        }
      }


