# TODO: remove this file; we moved to enviroment varibles in the docker-compose.
auth:
  type: LOGIN_FORM

spring:
  security:
    user:
      name: REDACTED
      password: REDACTED

kafka:
  clusters:
    - bootstrapServers: kafka:9092
      name: kafka

